### ISSUE TITLE
Adding Portuguese language

### ISSUE THREAD

**Issue by ferracioli** [mariokreitz/pokedex-v2#6]
Hello, 
I am just opening this issue in order to update my status with the page translation. I managed to swap the angullar ternary interpolations for dictionaries(like in the image below) in order to allow multiple languages. 
![image](https://github.com/user-attachments/assets/b4ef808e-7184-43cf-bf58-9b7b39a7ff74)

My progress is around 60% of page translation, and I will take some extra time to finish it. The future mapped challenges are:
- Style the language selector(it changed from switch to a select tag)
- Check if the PokeAPI has the portuguese language option(we brazilians never have titles with portuguese as official language :( )

Here is a preview of the page in portuguese
![image](https://github.com/user-attachments/assets/17706d50-9d74-48fc-96e7-0f4e19e17a06)

**Comment by mariokreitz** [comment]
It’s great to hear that you’ve managed to swap the Angular ternary interpolations for dictionaries to support multiple languages. This approach should streamline the translation process.

**Comment by mariokreitz** [comment]
The changes to the language selector (from switch to a select tag) sound like a good plan. Let me know if you need help checking if the PokeAPI supports Portuguese or if there are any other blockers in the process.

**Comment by mariokreitz** [comment]
I'm sorry for this, but nevertheless, it's totally fine if you want to add the Spanish translation.
I'm glad to hear again from you =) how's it going so far?

**Comment by ferracioli** [comment]
No worries :)
So I will continue with the spanish version. My code is up to 90% from total complete, so until tomorrow I will apply my pull request! In some parts of the code I couldn't use switch case instead of nested ternaries, but I did my best to change everywhere I could :D (this will allow future languages if we manage to get more programmers to the project)

**Comment by ferracioli** [comment]
Done, I finished the translation and added a pull request :D

I hope in the future we can get more language translations!
